# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadData(object):
    def setupUi(self, LoadData):
        LoadData.setObjectName("LoadData")
        LoadData.setWindowModality(QtCore.Qt.ApplicationModal)
        LoadData.resize(708, 481)
        self.centralwidget = QtWidgets.QWidget(LoadData)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(685, 350))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setStyleSheet("tableWidget.backgound.rgb(223, 223, 223)")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Btn_Refresh = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Refresh.setObjectName("Btn_Refresh")
        self.horizontalLayout.addWidget(self.Btn_Refresh)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        LoadData.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoadData)
        QtCore.QMetaObject.connectSlotsByName(LoadData)

    def retranslateUi(self, LoadData):
        _translate = QtCore.QCoreApplication.translate
        LoadData.setWindowTitle(_translate("LoadData", "MainWindow"))
        self.label.setText(_translate("LoadData", "Chọn bảng chấm"))
        self.Btn_Refresh.setText(_translate("LoadData", "Refresh"))
        self.pushButton.setText(_translate("LoadData", "Xem"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoadData = QtWidgets.QMainWindow()
    ui = Ui_LoadData()
    ui.setupUi(LoadData)
    LoadData.show()
    sys.exit(app.exec_())
