# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginUI(object):
    def setupUi(self, LoginUI):
        LoginUI.setObjectName("LoginUI")
        LoginUI.resize(400, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginUI.sizePolicy().hasHeightForWidth())
        LoginUI.setSizePolicy(sizePolicy)
        LoginUI.setMinimumSize(QtCore.QSize(300, 500))
        LoginUI.setMaximumSize(QtCore.QSize(400, 500))
        self.centralwidget = QtWidgets.QWidget(LoginUI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.loginframe = QtWidgets.QFrame(self.centralwidget)
        self.loginframe.setStyleSheet("#loginframe{\n"
"padding: 20px\n"
"}")
        self.loginframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginframe.setObjectName("loginframe")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.loginframe)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Btn_login = QtWidgets.QPushButton(self.loginframe)
        self.Btn_login.setMinimumSize(QtCore.QSize(0, 40))
        self.Btn_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_login.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.Btn_login.setObjectName("Btn_login")
        self.gridLayout_2.addWidget(self.Btn_login, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.loginframe)
        self.label.setMaximumSize(QtCore.QSize(400, 16777215))
        self.label.setStyleSheet("\n"
"font: 75 18pt \"MS Shell Dlg 2\"\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.loginframe)
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.Line_Password = QtWidgets.QLineEdit(self.loginframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Line_Password.sizePolicy().hasHeightForWidth())
        self.Line_Password.setSizePolicy(sizePolicy)
        self.Line_Password.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.Line_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Line_Password.setObjectName("Line_Password")
        self.verticalLayout_2.addWidget(self.Line_Password)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 4, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.loginframe)
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.Line_Username = QtWidgets.QLineEdit(self.loginframe)
        self.Line_Username.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Line_Username.sizePolicy().hasHeightForWidth())
        self.Line_Username.setSizePolicy(sizePolicy)
        self.Line_Username.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.Line_Username.setObjectName("Line_Username")
        self.verticalLayout.addWidget(self.Line_Username)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 7, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 5, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.loginframe, 0, 0, 1, 1)
        LoginUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginUI)
        QtCore.QMetaObject.connectSlotsByName(LoginUI)
        LoginUI.setTabOrder(self.Line_Username, self.Line_Password)
        LoginUI.setTabOrder(self.Line_Password, self.Btn_login)

    def retranslateUi(self, LoginUI):
        _translate = QtCore.QCoreApplication.translate
        LoginUI.setWindowTitle(_translate("LoginUI", "MainWindow"))
        self.Btn_login.setText(_translate("LoginUI", "Login"))
        self.label.setText(_translate("LoginUI", "ĐĂNG NHẬP HỆ THỐNG"))
        self.label_3.setText(_translate("LoginUI", "Password:"))
        self.Line_Password.setPlaceholderText(_translate("LoginUI", "Password"))
        self.label_2.setText(_translate("LoginUI", "Username:"))
        self.Line_Username.setPlaceholderText(_translate("LoginUI", "Username"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginUI = QtWidgets.QMainWindow()
    ui = Ui_LoginUI()
    ui.setupUi(LoginUI)
    LoginUI.show()
    sys.exit(app.exec_())
